# Generated by Django 5.0.6 on 2024-09-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_usuario_password_alter_usuario_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_alumno', models.CharField(max_length=10, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('plan', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=8)),
                ('correo', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=15)),
                ('escuela', models.CharField(max_length=100)),
            ],
        ),
    ]
