# Generated by Django 5.1.1 on 2024-10-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_id_alumno_id_alumno_alumno_ciclo_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='ciclo',
            field=models.IntegerField(default=1),
        ),
    ]
