# Generated by Django 5.1.1 on 2024-09-25 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alumno_escuela_plan_remove_usuario_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escuela',
            old_name='nombre_plan',
            new_name='nombre_escuela',
        ),
    ]
