# Generated by Django 5.1.1 on 2024-10-02 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_curso_prerrequisito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='ciclo',
            new_name='anio',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='ciclo',
            new_name='anio',
        ),
    ]
