# Generated by Django 5.1.1 on 2024-10-02 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_rename_ciclo_alumno_anio_rename_ciclo_curso_anio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoPrerrequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.curso')),
            ],
        ),
    ]
