# Generated by Django 5.1.1 on 2024-10-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_cursoprerrequisito'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='semestre',
            field=models.IntegerField(default=1),
        ),
    ]
