# Generated by Django 5.1.1 on 2024-10-02 19:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_curso_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursoprerrequisito',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
