# Generated by Django 5.1.1 on 2024-10-03 00:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_cursoprerrequisito_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boucher',
            fields=[
                ('id_boucher', models.AutoField(primary_key=True, serialize=False)),
                ('numero_boucher', models.CharField(max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id_matricula', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_matricula', models.DateField(default=django.utils.timezone.now)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.alumno')),
                ('boucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.boucher')),
                ('cursos', models.ManyToManyField(to='App.curso')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.plan')),
            ],
        ),
    ]
