# Generated by Django 5.0.6 on 2024-10-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_usuario_rol_consejero'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='estado',
            field=models.CharField(default='pendiente', max_length=20),
        ),
    ]
