# Generated by Django 5.0.6 on 2024-10-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_matricula_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='mensaje_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
