# Generated by Django 5.0.6 on 2024-10-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_matricula_mensaje_rechazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='mensaje_aprobacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
