# Generated by Django 5.1 on 2024-10-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_remove_matricula_boucher_matricula_boucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='cupos_disponibles',
            field=models.IntegerField(default=30),
        ),
    ]
