# Generated by Django 5.1.2 on 2024-10-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoucherBanco',
            fields=[
                ('id_boucher', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_boucher', models.CharField(max_length=10)),
                ('codigo_alumno', models.CharField(max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
