# Generated by Django 5.1.2 on 2024-12-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_boucherbanco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('alumno', 'Alumno')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Consejero',
        ),
    ]
